### ISSUE TITLE
npmBuild should default to `npm build`

### ISSUE THREAD

**Issue by yorickvP** [serokell/nix-npm-buildpackage#12]
Currently, `buildNpmPackage { src = ./.; }` also requires `npmBuild`, which has a sensible default in most cases. We should set it to `npm build`.

**Comment by zhenyavinogradov** [comment]
We happen to use `build` npm script for building in our projects, but there's no explicit rule in npm saying it should be like that, it could be any shell command you want to run with node_modules directory available. Making it the default command will make this behavior harder to discover
