### ISSUE TITLE
Make the prune call optional

### ISSUE THREAD

**Issue by freezeboy** [serokell/nix-npm-buildpackage#27]
# Goal
Let the caller avoid the call of npm prune --production

# Example

I tried the tool with [meta](https://github.com/mateodelnorte/meta).
It was blocking at the prune stage, because it wanted to read some remote (why???)

So in the end, my quick and dirty solution was to copy the installPhase + the tarAndUnwrap attributes to have a working package.

Thank you

**Comment by yorickvP** [comment]
Should be done now, using `{ dontNpmPrune = true; }`. 

npm prune seems to want to replace some pkgs sometimes, I gave it access to the cache, so it should just work now.
