### ISSUE TITLE
Unable to build package that uses dependency for building

### ISSUE THREAD

**Issue by Jomik** [serokell/nix-npm-buildpackage#5]
I am unable to build [coc.nvim](https://github.com/neoclide/coc.nvim) after he changed it to use `npm-run-all` for the `prepare` phase.
https://github.com/neoclide/coc.nvim/blob/72f98ad79d3afe60aea04d020abafe4995ba7cdb/package.json#L14
I get the following error `/bin/sh: npm-run-all: not found`.

```nix
buildYarnPackage {
  src = fetchFromGitHub {
    owner = "neoclide";
    repo = "coc.nvim";
    rev = "72f98ad79d3afe60aea04d020abafe4995ba7cdb";
    sha256 = "0i627b46kicrfkzpy2a5l3dzyp30qp58n5i4a95jif8pmm2phghp";
  };
}
```

**Comment by yorickvP** [comment]
This is a yarn bug, it doesn't run the custom script-shell for lifecycle scripts (such as 'prepare'), so our `patchShebangs` call does not run (which was a hack, anyways).
It looks like we can use their ['hooks'](https://github.com/yarnpkg/yarn/blob/master/__tests__/hooks.js) system to run patchShebangs after the `linkStep` to fix this in a better way, but it will require replacing the yarn call with some javascript.

**Comment by Jomik** [comment]
That would be nice - then I wouldn't have to patch those `package.json` files :P
Is this something you will be implementing, or should I look at a PR for it? I have no idea how yarn works though, as I do not use it personally.

**Comment by Jomik** [comment]
Amazing, thanks a lot :)
